name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test ${{ matrix.target }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: LINUX

          - os: windows-latest
            target: WINDOWS

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure
        run: >
          cmake
          -S .
          -B build
          -DCPPLIB_TARGET=${{ matrix.target }}
          -DCPPLIB_BUILD_TESTS=ON
          -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release --parallel

      - name: Test
        run: ctest --test-dir build -C Release --output-on-failure